EXEC_STATUS_IDLE = 0
EXEC_STATUS_PENDING = 10
EXEC_STATUS_RUNNING = 20
EXEC_STATUS_RETRY_WAIT = 30

EXEC_STATUS_TEXT_BY_CODE = {
    EXEC_STATUS_IDLE: "IDLE",
    EXEC_STATUS_PENDING: "PENDING",
    EXEC_STATUS_RUNNING: "RUNNING",
    EXEC_STATUS_RETRY_WAIT: "RETRY_WAIT",
}
