STATE_SUBAGENT_RUNNING = -300
STATE_TOOL_RESULT_READY = -200
STATE_USER_MESSAGE_READY = -100
STATE_WAIT_USER = 100
STATE_COMPLETED = 200
STATE_ARCHIVED = 300
STATE_FAILED = 1000

STATE_TEXT_BY_CODE = {
    STATE_SUBAGENT_RUNNING: "SUBAGENT_RUNNING",
    STATE_TOOL_RESULT_READY: "TOOL_RESULT_READY",
    STATE_USER_MESSAGE_READY: "USER_MESSAGE_READY",
    STATE_WAIT_USER: "WAIT_USER",
    STATE_COMPLETED: "COMPLETED",
    STATE_ARCHIVED: "ARCHIVED",
    STATE_FAILED: "FAILED",
}
